export const nftList = [
  {
    name: "Presale – Early Archaeologists",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/dino.gif",
    description:
      "66 million years ago, a meteorite hit our Earth and all dinosaur species perished. These dinosaurs, of which only bones remain, are being revived for display in metaverse museums. Archaeologists are combining bones and bringing dinosaurs back to life. Combining 6 different bone fragments, archaeologists create legendary dinosaurs. Archaeologists are discovering new species as they dig deeper. Join our family in the early stages! Join the friendly community right now and you’ll see for yourself",
    release: "12.03.2022",
    time: "00:00",
    type: "Drop",
    blockchain: "Matic",
    price: "-",
    supply: "-",
    website: "https://www.ancientdinosaurs.com/",
    discord: "https://discord.gg/MXNP74MQ",
    twitter: "https://twitter.com/AncientDinosNFT",
  },
  {
    name: "Mythical Creatures",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/gif-5.gif",
    description:
      "Mythical Creatures is an upcoming NFT collection on the Ethereum Blockchain consisting of 7,777 Mythical Creatures, with over 300+ traits, each NFT will feel unique. They are also creating an on-chain play-to-earn (P2E) game called “Mythical Dreamland,” based on Alice’s Adventures in Wonderland with their utility token called ALICE. Travel through Mythical Dreamland P2E to earn $ALICE token. Will you stop to get the help of your friends or will you go alone? The artist behind this collection is named Ed Dinzole. He has worked with large networks such as TNT, FOX, Adult Swim, and more. Not only are they doing their P2E game, they are also creating their own smart contract, ERC721M. ERC721M is a new NFT contract format created by Tessera Labs with the intention of greatly reducing costs related to participating in our game for those with many NFTs. To learn more about Mythical Creatures, follow them on Twitter or join their Discord with the links provided.",
    release: "11.03.2022",
    time: "00:00",
    type: "Drop",
    blockchain: "Ethereum",
    price: "-",
    supply: "7777",
    website: "https://www.mythicalcreaturesnft.com/",
    discord: "https://discord.gg/mythicalcreatures",
    twitter: "https://twitter.com/Mythical_NFT",
  },
  {
    name: "Succubus Syndicate Whitelist",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/gif-x10.gif",
    description:
      "Succubus Syndicate aims to build an adult-oriented ecosystem that benefits all parties involved by empowering content creators while allowing the consumer to fully immerse themselves in the world of adult content. Our goal is to bridge the gap between the adult-entertainment industry and blockchain technology to create the premier platform for NSFW content on Solana.\n\nProject Highlights:\nStake to Earn $SUCC \nMetaverse Red Light Distric (P2E)\nNSFW Marketplace\nAdult-Content Platform",
    release: "11.03.2022",
    time: "00:00",
    type: "Drop",
    blockchain: "Solana",
    price: "-",
    supply: "-",
    website: "https://succubussyndicate.com/",
    discord: "https://discord.gg/SuccubusSyndicate",
    twitter: "https://twitter.com/SuccubusSynNFT",
  },
  {
    name: "Meet Cardano Skate Club",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/HomePageGif.gif",
    description:
      "Hello skaters! We would like to introduce to you Cardano Skate Club. A group of NFT collections based on Cardano blockchain. Each season has its own special use case, all of which will be a part of our final version of the project. We plan on releasing multiple NFT seasons all within the theme of skateboarding.",
    release: "11.03.2022",
    time: "00:00",
    type: "Drop",
    blockchain: "Cardano",
    price: "33 ADA",
    supply: "5005",
    website: "https://cardanoskateclub.com/",
    discord: "https://discord.gg/TbvHsZyEhW",
    twitter: "https://twitter.com/CardanoSkate",
  },
  {
    name: "SKULLATION",
    logo: "https://nftiming.com/wp-content/uploads/2022/03/promo-gif.gif",
    description:
      "Skullation is a unique NFT collection. All items is collectibles living on the Polygon blockchain, stored as ERC-1155 tokens and hosted on IPFS. Skullation can be bought and resold on the OpenSea with No Gas Fee! Rarities Skullation is one of the few collections on OpenSea, where you can search between certain numbers, special numbers and rarity. We have spend a lot of time in developing and creating this filter system. The rarity of the characters depends on the probability of the 6 main parts coming together. These 6 main element contain the following numbers of sub-items, and their rarity is automatically determined at the rate the item's use in the collection. Community will grow its at an affordable starting price and this will increase demand. Members will get new benefits, unique PFP, access to community rooms and more.\n\nSTORY:\n\nAfter a very harsh sea age, Pirate skulls surviving unknowingly on a lost island. Now, they need to explore the world, create inventions; different cloths, styles, appearance and generes for a new world! Skullation collection is randomly generated unique skull characters minted on the Blockchain. The collection will consist of 3,333 pieces different skull characters. 33 of them will be very special editions of the collection and fully hand-drawn like the others. They have +900k possible combinations and a variety of facial expressions, outfits, items, ranks, backgrounds and hats.",
    release: "10.03.2022",
    time: "12:00",
    type: "Drop",
    blockchain: "Ethereum",
    price: "0.003",
    supply: "3333",
    website: "https://www.skullation.com/",
    discord: "https://discord.gg/sVXhDB2gt2",
    twitter: "https://twitter.com/Skullation_NFT",
  },
  {
    name: "Wave Surfers Club",
    logo: "https://nftiming.com/wp-content/uploads/2022/03/83.png",
    description:
      "Hop on the waves with the hottest NFT collection of 2022: Wave Surfers Club! The uber-sick limited collection is made of 111 male and 111 female surfers; limited to 222 art pieces only.\n\nInspired by the beautiful Bangko-Bangko beach in Lombok - Indonesia, Wave Surfers Club is the only pixel surf art collection on Secret Network.\n\nA surfing heaven showcasing the best pipeline in the world, Bangko Bangko is a must stop if you are into surfing. However, Wave Surfers Club NFT collection is much more than just great waves for surfers. We have built our community based on trust, privacy and value.\n\nHolders of the Wave Surfers Club NFTs will have access to more than they would ever imagine including staking rewards, access to special events and suprise NFTdrops.\n\nRemember; there is no one right way to ride a wave! Owning one of the Wave Surfers Club NFTs may be the best ride of your life. May the water element bring you a surfers best life…",
    release: "10.03.2022",
    time: "12:00",
    type: "Drop",
    blockchain: "Other",
    price: "20 SECRET",
    supply: "222",
    website: "https://wavesurfers.club/",
    discord: "https://discord.gg/wavesurfersclub",
    twitter: "https://twitter.com/WaveSurfersClub",
  },
  {
    name: "SpaceChicks",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/1-20.jpg",
    description:
      "SpaceChicksNFT!\nThis project is devoted to such global problems as discrimination against women and the ecological crisis. Our mission is to raise awareness of the environmental issues and to destroy the common stereotype that the crypto world belongs to men. 4444 Space Chicks are here to help us.\n\nWelcome on board!\nIt was 2030 and life on Earth had become unbearable.\nThe planet was suffering from pollution and epidemics of new viruses.\nA squad of 4444 unique Space chicks was sent in search of a new crypto planet, TeslaX.\nThe journey will be long, so each chick took the most necessary equipment for developing a new place to live.\nThis project has gathered people who love Space Chicks. We believe that due to a common vision,we will be able to create a community that will change the lives of all participants.\n\nPrice for VIP list members is 0.06 ETH\nPrice for White list members is 0.07 ETH",
    release: "10.03.2022",
    time: "00:00",
    type: "Drop",
    blockchain: "Ethereum",
    price: "0.06 / 0.07 ETH",
    supply: "4444",
    website: "https://spacechicksnft.com/",
    discord: "https://discord.com/invite/spacechicks",
    twitter: "https://twitter.com/SpaceChicksNFT",
  },
  {
    name: "Lonely Dogs",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/%D0%93%D0%B8%D1%84%D0%BA%D0%B0-%D1%81-%D1%81%D0%B0%D0%B9%D1%82%D0%B0.gif",
    description:
      "According to statistics of 2021, more than 5,500 dogs suffer from lack of space in shelters every day in the USA alone and how many are there all over the planet? In order to help the dogs in the Old world’ it was decided to send 5,500 Lonely Dogs to the metaverse so that they could find their owners and help to solve the problem in the Old world. Together with the Lonely Dogs community we will be able to implement an application for donations with the HelPPets token in all animal care organizations in the world. \n Collection consists of 5,500 unique NFT arts. \n When will the official mint take place? \n Lonely Dogs pre-sale will take place Thursday Mar 10th 8:00pm UTC, public sale will take place 9:00pm UTC. \n Presale price is 1.3 SOL, public sale price – 1.5 SOL. \n Does Lonely Dogs have a Whitelist? \n Yes, there is a Whitelist, the most active members of the community will get into it. There are 750 spots on the Whitelist.",
    release: "10.03.2022",
    time: "00:00",
    type: "Drop",
    blockchain: "Solana",
    price: "1.3 / 1.5 SOL",
    supply: "5500",
    website: "https://lonelydogsnft.io/",
    discord: "https://discord.com/invite/aUagT3pvsP",
    twitter: "https://twitter.com/lonely_dogs_nft",
  },
  {
    name: "ApeDoodles",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/ad-gif.gif",
    description:
      "10,000 apes looking for a new home! \n 25% After four months of preparation, Planet of the Doodled Apes will launch 10,000 Doodled Apes on March 9, 2022! \n 50% We will be sending 50 Doodle Apes and 5 Iron Apes to our community members who have always trusted and supported us! \n 75% The community is already functioning in the right way. We will give back 500 Graffiti Apes + 10 Iron Apes to the community. \n 100% We have reached a great moment! All the apes have found their place. At that time, we will give back 1000 graffiti apes + 20 steel apes to the community. \n May the apes be with us!",
    website: "https://hypersloths.com/",
    release: "09.03.2022",
    time: "00:00",
    type: "Update",
    blockchain: "Ethereum",
    price: "-",
    supply: "10,000",
    discord: "https://discord.gg/72UKpxEbnE",
    twitter: "https://twitter.com/ApedoodlesNFT",
  },
];
