export const nftList = [
  {
    name: "HYPERSLOTHS™",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/GIF-Hypersloths-2.gif",
    description:
      "With a world class artist Yevgeni Krachak in the lead, a one-of-a-kind Collect-To-Earn utility and a doxxed team - this project is here for the long run. The HYPERSLOTHS are the perfect representation of the ‘work hard play hard’ mentality and they bring way more than world class 3D art. This collection of 8000 3D art pieces will make your day to day collecting experience exciting like never before With a utility that delivers a punch every single week! Solve riddles >>> collect HYPERSLOTHS >>> Claim prizes - it’s so simple, an ape can understand. Join HYPERSLOTHS - ART. UTILITY. COMMUNITY.",
    website: "https://hypersloths.com/",
    release: "24.02.2022",
    time: "00:00",
    type: "Update",
    blockchain: "Ethereum",
    price: "0.25 ETH",
    supply: "150",
    discord: "https://discord.gg/hypersloths",
    twitter: "https://twitter.com/HYPER_SLOTHS",
  },
  {
    name: "Novatar",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/nftiming.gif",
    description:
      "The Novatar is a limited collection of 25k NFT avatars that will grow up on the blockchain and will transform from a baby into an adult. - All 25k Novatars are newborn babies. - Novatar illustrations are AI generated and represent the diversity of race, gender, sexual orientation also expressing emotions through facial expressions. - The Novatar owner decides to either age the Novatar or not. This process is irreversible. - Novatars have a variety of basic, as well as, appearing genes. The collection of genes differs depending on the age of the NFT: adults have more genes. - Some adult Novatars can have genes for profession: developer, gamer, astronaut, doctor, or blogger. Novatars can be used as profile pic NFTs on all social media platforms. Usability: Use your Novatar as an NFT profile pic on Twitter and other social media (when available), find your Meta Identity. This is a unique collection of 25k avatars which can age on the blockchain. Rarity: Novatars have a unique rarity system, with some of them having unique genes as profession.",
    website: "https://thenovatar.com/",
    release: "27.02.2022",
    time: "19:00",
    type: "Drop",
    blockchain: "Ethereum",
    supply: "25000",
    price: "0.1 ETH",
    discord: "https://discord.com/invite/u62rRVSKK4",
    twitter: "https://twitter.com/thenovatar",
  },
  {
    name: "Burglar Ape Club",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/ape-low.png",
    description:
      "Meet the Burglar Ape Club a collection of 5000 NFTs minted on the polygon blockchain. Pay what you want for the first 400 owners, At 400 owners (or sold out) the art will be REVEALED. after reveal mint price will be 0.001. All the arts have been created by professionals, in the future a mutation system will be established. You can ask us any questions through any of our social networks. Join the discord for more info, roadmap, and poolls!",
    website: "23.02.2022",
    release: "24.02.2022",
    time: "00:00",
    type: "Drop",
    blockchain: "Matic",
    price: "0.001 MATIC",
    supply: "5000",
    discord: "https://discord.gg/CJGwAckQ",
    twitter: "https://twitter.com/BurglarApeClub",
  },
  {
    name: "League of Miners",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/2764.png",
    description:
      "We are “League Of Miners” – a DeFi focused NFT company with a long-term plan. With our genesis NFT collection “League of Miners” we want to set the course for a strong brand. We plan to invest a large proportion of sales into Ethereum stake pools and other blockchains, to hope for an ongoing influx of funds for continuous development. 11111 Miners will be released on 02/28/2022.",
    website: "https://leagueofminers.com/",
    release: "28.02.2022",
    time: "18:00",
    type: "Drop",
    blockchain: "Ethereum",
    price: "0.08 ETH",
    supply: "1111",
    discord: "https://discord.gg/uzrVH6ET8D",
    twitter: "https://twitter.com/LOMiners",
  },
  {
    name: "The Pigorilla Club",
    logo: "https://nftiming.com/wp-content/uploads/2022/02/ezgif.com-gif-maker-1-1.gif",
    description:
      "The Pigorilla Club is an NFT community ready to be the leader of activism in the virtual universe. This NFT aims to raise awareness of anti-bullying & body positivity and make the Pigorilla the icon of stomping out bullying. Owners of these NFTs will be able to get a piece of history by claiming a future classic that will become the icon of activism in the virtual world, in addition to it going towards a charitable cause that is necessary in these technological advances. A portion of the proceeds from the Pigorilla go towards top anti-cyberbullying and body positivity foundations like “The Body Positive”, “Love Your Body” and “CyberSmile”. This community aims to make the virtual universe an inclusive environment for all through collaborative actions and movements. Pigorilla NFT owners can expect inclusive in-person events and partnerships to support the mission of making the virtual universe safe for all. It is launching on National Anti-Bullying Day 2/23/2022 at 7PM EST on Opensea in the Polygon blockchain.",
    website: "https://opensea.io/ThePigorillaClub",
    release: "24.02.2022",
    time: "00:00",
    type: "Drop",
    blockchain: "Polygon",
    price: "$50 USD",
    supply: "",
    discord: "https://discord.gg/uGChpgJnUw",
    twitter: "https://twitter.com/Pigorilla_NFT",
  },
];
