export const members = [
  {
    id: "timnik",
    username: "Timnik",
    name: "Ungureanu Calin Petru",
    profilePic: "/images/team/timnik.png",
    github: "nottimnik",
    twitter: "nottimnik",
    instagram: "nottimnik",
    medium: "timnik",
    position: "CEO, Founder & Developer",
    description: "",
  },
  {
    id: "luke",
    username: "Luke",
    name: "Ungureanu Luca Tudor",
    profilePic: "/images/team/luke.png",
    github: "",
    twitter: "",
    instagram: "",
    medium: "",
    position: "Co-Founder & Social Media Manager",
    description: "",
  },
  {
    id: "chris",
    username: "Chris",
    name: "Bordei Christian Andrei",
    profilePic: "/images/team/chris.png",
    github: "",
    twitter: "",
    instagram: "",
    medium: "",
    position: "Advisor & Writer",
    description: "",
  },
];
